In [1]:
import numpy as np

In [2]:
a= np.arange(1,12) #-1 tk

In [3]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
#chain function
# first internal function
# A(B(c(2)))
#first c then b than a will execute

In [6]:
# In numpy 
# A().b().C()
# first a, b,c respectively

In [7]:
a= np.arange(1,13).reshape(3,4) 
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
a.dtype

dtype('int32')

In [9]:
a=a.astype(np.float64)


In [10]:
a.dtype

dtype('float64')

In [11]:
#efficent code less function
a= np.arange(1,13 , dtype=np.float64).reshape(3,4)
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [12]:
np.random.rand(3,3)

array([[0.64224661, 0.23489241, 0.67222795],
       [0.67426311, 0.90107307, 0.25202892],
       [0.0377366 , 0.06187064, 0.64510809]])

In [13]:
np.random.rand(3,3)*5 # random but mul with 5

array([[3.26594091, 2.99510147, 1.58957765],
       [1.34706926, 4.53991027, 2.21122906],
       [2.10119467, 2.90598864, 4.90363693]])

In [14]:
a= np.ones([3,3,3], dtype=np.float64) #every value=1
a

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [15]:
a.shape


(3, 3, 3)

# for previous dimension use zero_like/ones like

In [16]:
a= np.ones([3,3,3], dtype=np.float64)
a

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [17]:
a*5

array([[[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]]])

In [18]:
np.zeros_like(a)

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
a= np.ones([3,3,3], dtype=np.float64)*5
a

array([[[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]]])

# Another/second way to fill with any other values as 1,0,5 without using zeros, ones and multiply

In [22]:
c=np.full((3,3,3),2) # second way
c

array([[[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

In [23]:
np.full_like(c,10)

array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

In [39]:
# empty 0 and garbage value picks, its for random value +garbage

In [24]:
np.empty((4,4,4))

array([[[2.49997217e-321, 0.00000000e+000, 4.94065646e-324,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 9.55661945e-299, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+0

In [26]:
np.empty_like(c) #not correct

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

# eye/identity for daignol

In [47]:
np.eye(6) #has more attributes

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [48]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
#before that all functions narray, arrange mein calculate krna parta

# to show help for anything use double question mark
np.eye??
for detail

# Data type changes

In [51]:
a= np.arange(1,13, dtype='i8') #dtype i4=int 32
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int64)

In [55]:
a= np.arange(1,13, dtype='f8') #dtype i4=int 32
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [56]:
a= np.arange(1,13, dtype='float64') #dtype i4=int 32
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [62]:
a= np.arange(1,28, dtype='float64').reshape(3,3,3)
print(a)
print(a.dtype)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]]

 [[10. 11. 12.]
  [13. 14. 15.]
  [16. 17. 18.]]

 [[19. 20. 21.]
  [22. 23. 24.]
  [25. 26. 27.]]]
float64


In [66]:
np.full_like(a,5, dtype=a.dtype)

array([[[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]]])

In [68]:
a=np.arange(1,28).reshape(3,3,3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [27]:
# mathematical calulations

In [69]:
a%3==0

array([[[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]]])

In [70]:
a[a%3==0]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [75]:
a[(a%3==0) | (a%5==0)]

array([ 3,  5,  6,  9, 10, 12, 15, 18, 20, 21, 24, 25, 27])

In [76]:
a[(a%3==0) & (a%5==0)]

array([15])

In [78]:
a[(-a%3==0)]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

# Basic indexing and slicing

In [ ]:
#   1 range, axis, dim) 2-condition bolean ,3- fancy slicing. har dim m array list pass kerty