In [1]:
%history


%history


In [4]:
print("Line1")
print("Line2")

Line1
Line2


In [4]:
#%load Numpy.py
print("Line1")
print("Line2")

ValueError: 'Numpy.py' was not found in history, as a file, url, nor in the user namespace.

In [3]:
%run filename.py


ERROR:root:File `'filename.py'` not found.


In [4]:
%history


print("Line1")
print("Line2")
%run Numpy.py
%run filename.py
%history


In [5]:
%time sum([1,3,4])


Wall time: 0 ns


8

# Python Vs Numpy¶


In [6]:
%time l1 = list(range(1,3000000))


Wall time: 90.4 ms


In [7]:
[x+5 for x in l1][:10]

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [8]:
%time [x+5 for x in l1][:10]


Wall time: 531 ms


[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

# Enumerate

In [16]:
list(enumerate(['a','b','c']))

[(0, 'a'), (1, 'b'), (2, 'c')]

In [19]:
list(enumerate(['A','B',"C"]))


[(0, 'A'), (1, 'B'), (2, 'C')]

In [9]:
for i,v in list(enumerate(l1)):
    l1[i]=l1[i]+5
l1[:10]    

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [11]:
for i,v in list(enumerate(l1)):
    l1[i] = l1[i]+5
l1[:10]

[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

# for  Addition in simple python too big code

In [10]:

a = [[1,2,3],
    [4,5,6],
    [7,8,9]]

print("Before Adding 5")
print(a)
for ri, rd in list(enumerate(a)):
    for ci, cd in list(enumerate(rd)):
        a[ri][ci] += 5
        

print("After Adding 5")
print(a)

Before Adding 5
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
After Adding 5
[[6, 7, 8], [9, 10, 11], [12, 13, 14]]


In [11]:
# it was not possible to simple add list/array
a = [1,2,3]
a + 5

TypeError: can only concatenate list (not "int") to list

# Numpy


In [13]:
import numpy as np


In [14]:
%time l2 = np.arange(1,3000000)


Wall time: 9.97 ms


In [15]:
l1 = np.array([1])
print("Dimension:", l2.ndim)
print("Shape:", l2.shape)
print("Type:", l2.dtype)

Dimension: 1
Shape: (2999999,)
Type: int32


In [26]:
l1 = np.random.randn(2,2)
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)
#l1[row,col]

[[-0.83554632 -0.28220271]
 [-0.90457817  1.13757011]]
Dimension: 2
Shape: (2, 2)
Type: float64


In [27]:
l1 = np.random.randn(3,3,3)
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)

[[[ 1.08132278  0.56461414 -0.1331651 ]
  [-0.50959732  0.73880521 -0.43303517]
  [ 0.69596368  0.4084376  -0.40793724]]

 [[ 0.26295631  1.79463521 -0.25609587]
  [-0.88156934 -0.95731231  0.45831443]
  [-0.16792061  0.04196872  0.92422753]]

 [[-0.52679498 -1.1645016  -1.07212646]
  [ 0.98711072 -0.69900185 -0.40344924]
  [ 2.53497034  0.40868595 -0.66853449]]]
Dimension: 3
Shape: (3, 3, 3)
Type: float64


In [21]:
l1 = np.arange(27).reshape((3,3,3))
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Dimension: 3
Shape: (3, 3, 3)
Type: int32


In [22]:
l1[1,2,1] # slicing to find 16 

16

In [24]:
#l1[i,j,k]
#3 x 3

In [25]:
#By numpy we dont require bi loops. we can simply add

In [26]:
l1 = np.arange(27).reshape((3,3,3))
print(l1)

l1 = l1 + 5
l1

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 5,  6,  7],
        [ 8,  9, 10],
        [11, 12, 13]],

       [[14, 15, 16],
        [17, 18, 19],
        [20, 21, 22]],

       [[23, 24, 25],
        [26, 27, 28],
        [29, 30, 31]]])

In [27]:
l1 = np.arange(1,11)
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
Dimension: 1
Shape: (10,)
Type: int32


In [32]:
l1 = np.arange(1,26).reshape((5,5))
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Dimension: 2
Shape: (5, 5)
Type: int32


In [33]:
l1 = np.random.randn(3,3,3,3,3)
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("itemsize", l1.itemsize) # bit/byte
print("Type:", l1.dtype)

[[[[[-0.68596102 -0.32324662  1.75437807]
    [ 0.64047319 -1.11567314 -0.49069156]
    [-0.49809203 -2.31861832 -1.68188795]]

   [[ 0.72634309 -1.38872678  0.65637567]
    [-0.28424884 -0.11452334 -0.26624317]
    [-1.35018258  1.81731295  0.86259955]]

   [[-1.16505489 -0.62210759 -0.57560797]
    [-1.2925079   0.77009441 -1.80454014]
    [ 0.91074486 -0.28412084 -0.40926706]]]


  [[[-1.18093012  0.49916778 -1.26778224]
    [ 0.04427936  1.0384655  -1.30098248]
    [ 1.12326119  0.81285595 -0.34501932]]

   [[ 1.70143547 -0.20911185  1.10962153]
    [-0.91896905 -2.11439126  0.75640027]
    [-0.27610916 -0.84205812 -0.48901917]]

   [[ 0.66658894  1.40728771 -0.04641093]
    [-0.15743856  0.26163259  1.04795801]
    [ 0.34082122  0.98977344 -0.58832334]]]


  [[[ 2.02969101  1.15016691 -0.0860614 ]
    [-0.0307547   0.06937256  0.12019587]
    [-1.73289086  1.68769181 -0.6082371 ]]

   [[-0.40228004  0.65116331  0.4157602 ]
    [ 1.39659554  1.53583045  1.6394926 ]
    [-0.8218362 

In [34]:
a = np.arange(1,28).reshape((3,3,3))
print(a ** .5)

[[[1.         1.41421356 1.73205081]
  [2.         2.23606798 2.44948974]
  [2.64575131 2.82842712 3.        ]]

 [[3.16227766 3.31662479 3.46410162]
  [3.60555128 3.74165739 3.87298335]
  [4.         4.12310563 4.24264069]]

 [[4.35889894 4.47213595 4.58257569]
  [4.69041576 4.79583152 4.89897949]
  [5.         5.09901951 5.19615242]]]


# Creating ndarrays¶


# np.array

In [33]:
# Deep Copy
l = [1,2,3]
print(type(l))

a = np.array(l)
b = np.array(a)

print(a is b)
type(a)
# #array m deep copy


<class 'list'>
False


numpy.ndarray

# np.asarray

In [34]:
# 1 array->Shallow Copy
# 2 array->Change dtype -> Deep Copy
# 3 if not array->Deep copy
l = [1,2,3]
print(type(l))

a = np.asarray(l) #2
b = np.asarray(a) #1
c = np.asarray(a, dtype=np.float64)#3

print(a is b) # 2
print(l is a) # 1
print(c is a) # 3
type(a)

<class 'list'>
True
False
False


numpy.ndarray

In [35]:
%history

%time [x+5 for x in l1][:10]
[x+5 for x in l1][:10]
[x+5 for x in l1][:10]
print("Line1")
print("Line2")
%time sum([1,3,4])
%time l1 = list(range(1,3000000))
[x+5 for x in l1][:10]
%time [x+5 for x in l1][:10]
for i,v in list(enumerate(l1)):
    l1[i]=l1[i]+5
l1[:10]

a = [[1,2,3],
    [4,5,6],
    [7,8,9]]

print("Before Adding 5")
print(a)
for ri, rd in list(enumerate(a)):
    for ci, cd in list(enumerate(rd)):
        a[ri][ci] += 5
        

print("After Adding 5")
print(a)
# it was not possible to simple add list/array
a = [1,2,3]
a + 5
l1 = np.array([1])
print("Dimension:", l2.ndim)
print("Shape:", l2.shape)
print("Type:", l2.dtype)
import numpy as np
%time l2 = np.arange(1,3000000)
l1 = np.array([1])
print("Dimension:", l2.ndim)
print("Shape:", l2.shape)
print("Type:", l2.dtype)
l1[i,j,k]
l1 = np.arange(27).reshape((3,3,3))
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)

l1[1,2,1]
l1 = np.arange(27).reshape((3,3,3))
print(l1)
print("Dim